import json
import subprocess
from abc import ABC, abstractmethod
from urllib import request

from app.models import ToolDefinition, ToolInvocationRequest, ToolResult
from app.services.card_factory import HtmlCardFactory


class ToolInvocationError(RuntimeError):
    pass


class ToolInvoker(ABC):
    @abstractmethod
    def invoke(self, tool: ToolDefinition, payload: ToolInvocationRequest) -> ToolResult:
        raise NotImplementedError


class BuiltinToolInvoker(ToolInvoker):
    def __init__(self, card_factory: HtmlCardFactory | None = None) -> None:
        self._card_factory = card_factory or HtmlCardFactory()

    def invoke(self, tool: ToolDefinition, payload: ToolInvocationRequest) -> ToolResult:
        if tool.id == "hello-world":
            card = self._card_factory.create(
                prompt=payload.prompt,
                source_tool_id=tool.id,
                name="Hello World",
            )
            card = card.model_copy(
                update={
                    "html": """<section style="display:grid;width:100%;height:100%;place-items:center;background:#111111;color:#ffffff;font-family:DM Sans,Inter,Arial,sans-serif;">
  <div style="display:grid;gap:8px;text-align:center;">
    <strong style="font-size:28px;line-height:1.2;">Hello world</strong>
    <span style="color:rgba(255,255,255,.7);font-size:13px;">Generated by the Hello World built-in tool</span>
  </div>
</section>"""
                }
            )
            return ToolResult(cards=[card])

        card = self._card_factory.create(
            prompt=payload.prompt,
            source_tool_id=tool.id,
            name=f"{tool.name} card",
        )
        return ToolResult(cards=[card])


class HttpToolInvoker(ToolInvoker):
    def invoke(self, tool: ToolDefinition, payload: ToolInvocationRequest) -> ToolResult:
        if not tool.permissions.network:
            raise ToolInvocationError("Tool does not have network permission.")
        if not tool.runtime.entrypoint:
            raise ToolInvocationError("HTTP tool is missing an endpoint.")

        body = payload.model_dump(by_alias=True)
        http_request = request.Request(
            tool.runtime.entrypoint,
            data=json.dumps(body).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method=tool.runtime.method,
        )

        with request.urlopen(http_request, timeout=tool.runtime.timeout_seconds) as response:
            response_body = response.read().decode("utf-8")

        return ToolResult.model_validate_json(response_body)


class CliToolInvoker(ToolInvoker):
    def invoke(self, tool: ToolDefinition, payload: ToolInvocationRequest) -> ToolResult:
        if not tool.permissions.filesystem:
            raise ToolInvocationError("Tool does not have filesystem permission.")
        if not tool.runtime.command:
            raise ToolInvocationError("CLI tool is missing a command.")

        command_name = tool.runtime.command[0]
        if command_name not in tool.permissions.allowed_commands:
            raise ToolInvocationError("CLI command is not allowed by tool permissions.")

        completed_process = subprocess.run(
            tool.runtime.command,
            input=json.dumps(payload.model_dump(by_alias=True)),
            capture_output=True,
            check=False,
            encoding="utf-8",
            timeout=tool.runtime.timeout_seconds,
        )

        if completed_process.returncode != 0:
            raise ToolInvocationError(completed_process.stderr.strip() or "CLI tool failed.")

        return ToolResult.model_validate_json(completed_process.stdout)


class ToolInvokerFactory:
    def __init__(self) -> None:
        self._builtin = BuiltinToolInvoker()
        self._http = HttpToolInvoker()
        self._cli = CliToolInvoker()

    def get_invoker(self, source_type: str) -> ToolInvoker:
        if source_type == "builtin":
            return self._builtin
        if source_type == "http":
            return self._http
        if source_type in {"cli-local", "cli-remote"}:
            return self._cli

        raise ToolInvocationError(f"Unsupported tool source type: {source_type}")
