import json
import re
import subprocess
from abc import ABC, abstractmethod
from html import escape
from urllib import request

from app.models import ToolDefinition, ToolInvocationRequest, ToolResult
from app.services.card_factory import HtmlCardFactory
from app.services.comfy_diffusion import ComfyDiffusionService


class ToolInvocationError(RuntimeError):
    pass


class ToolInvoker(ABC):
    @abstractmethod
    def invoke(self, tool: ToolDefinition, payload: ToolInvocationRequest) -> ToolResult:
        raise NotImplementedError


class BuiltinToolInvoker(ToolInvoker):
    def __init__(self, card_factory: HtmlCardFactory | None = None) -> None:
        self._card_factory = card_factory or HtmlCardFactory()

    def invoke(self, tool: ToolDefinition, payload: ToolInvocationRequest) -> ToolResult:
        if tool.id == "comfy-runtime-check":
            return self._invoke_comfy_runtime_check(tool, payload)

        if tool.id == "image" and isinstance(payload.params.get("imageDataUrl"), str):
            image_data_url = payload.params["imageDataUrl"]
            if not image_data_url.startswith("data:image/"):
                raise ToolInvocationError("imageDataUrl must be a data:image URL.")

            card = self._card_factory.create(
                prompt=payload.prompt,
                source_tool_id=tool.id,
                name=payload.params.get("name") or "Generated Image",
            )
            escaped_prompt = escape(payload.prompt)
            escaped_image_data_url = escape(image_data_url, quote=True)
            card = card.model_copy(
                update={
                    "html": f"""<section style="display:grid;width:100%;height:100%;place-items:center;background:#111111;color:#ffffff;font-family:DM Sans,Inter,Arial,sans-serif;overflow:hidden;">
  <figure style="display:grid;width:100%;height:100%;grid-template-rows:1fr auto;margin:0;background:#202020;">
    <div style="display:grid;min-height:0;place-items:center;padding:18px;">
      <img src="{escaped_image_data_url}" alt="{escaped_prompt}" style="display:block;max-width:100%;max-height:100%;object-fit:contain;border-radius:16px;" />
    </div>
    <figcaption style="padding:14px 18px 18px;color:rgba(255,255,255,.72);font-size:14px;line-height:1.45;">{escaped_prompt}</figcaption>
  </figure>
</section>"""
                }
            )
            return ToolResult(cards=[card])

        if tool.id == "hello-world":
            message = self._resolve_card_output_text(payload, fallback="Hello world")
            card = self._card_factory.create(
                prompt=payload.prompt,
                source_tool_id=tool.id,
                name="Hello World",
            )
            escaped_message = escape(message)
            card = card.model_copy(
                update={
                    "html": f"""<section style="display:grid;width:100%;height:100%;place-items:center;background:#111111;color:#ffffff;font-family:DM Sans,Inter,Arial,sans-serif;">
  <div style="display:grid;gap:8px;text-align:center;">
    <strong style="font-size:28px;line-height:1.2;">{escaped_message}</strong>
    <span style="color:rgba(255,255,255,.7);font-size:13px;">Generated by the Hello World built-in tool</span>
  </div>
</section>"""
                }
            )
            return ToolResult(cards=[card])

        card = self._card_factory.create(
            prompt=payload.prompt,
            source_tool_id=tool.id,
            name=f"{tool.name} card",
            output_text=self._resolve_card_output_text(payload, fallback=payload.prompt),
        )
        return ToolResult(cards=[card])

    def _resolve_card_output_text(self, payload: ToolInvocationRequest, *, fallback: str) -> str:
        for key in ("text", "message", "title", "content", "outputText"):
            value = payload.params.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()

        tool_prompt = payload.params.get("toolPrompt")
        prompt = tool_prompt.strip() if isinstance(tool_prompt, str) and tool_prompt.strip() else payload.prompt.strip()
        if not prompt:
            return fallback

        quoted_match = re.search(r"[\"'“”‘’]([^\"'“”‘’]{1,120})[\"'“”‘’]", prompt)
        if quoted_match:
            return quoted_match.group(1).strip()

        keyword_match = re.search(
            r"(?:diga|decir|diciendo|texto|contenido|says?|with text)\s+(?:exactamente\s+)?(.{1,120})",
            prompt,
            flags=re.IGNORECASE,
        )
        if keyword_match:
            message = keyword_match.group(1).strip()
            message = re.split(r"[.;\n]", message, maxsplit=1)[0].strip()
            message = message.strip(" \"'“”‘’")
            if message:
                return message

        return fallback

    def _invoke_comfy_runtime_check(self, tool: ToolDefinition, payload: ToolInvocationRequest) -> ToolResult:
        service = ComfyDiffusionService()
        runtime_info = service.get_runtime_info()
        status = "error" if runtime_info.get("error") else "ok"
        status_label = "Runtime error" if status == "error" else "Runtime ready"

        rows = [
            ("Status", status_label),
            ("ComfyUI version", runtime_info.get("comfyui_version") or "Unknown"),
            ("Device", runtime_info.get("device") or "Unknown"),
            ("VRAM total", self._format_megabytes(runtime_info.get("vram_total_mb"))),
            ("VRAM free", self._format_megabytes(runtime_info.get("vram_free_mb"))),
            ("Python", runtime_info.get("python_version") or "Unknown"),
            ("Models dir", runtime_info.get("modelsDir") or "Unknown"),
            ("Models dir exists", str(runtime_info.get("modelsDirExists", False))),
        ]
        if runtime_info.get("error"):
            rows.append(("Error", runtime_info["error"]))

        rows_html = "\n".join(
            f"""      <div style="display:grid;grid-template-columns:132px 1fr;gap:10px;padding:8px 0;border-bottom:1px solid rgba(255,255,255,.08);">
        <dt style="color:rgba(255,255,255,.56);">{escape(label)}</dt>
        <dd style="margin:0;color:#ffffff;word-break:break-word;">{escape(str(value))}</dd>
      </div>"""
            for label, value in rows
        )
        raw_json = escape(json.dumps(runtime_info, indent=2, sort_keys=True), quote=False)

        card = self._card_factory.create(
            prompt=payload.prompt,
            source_tool_id=tool.id,
            name="Comfy Runtime Check",
        )
        card = card.model_copy(
            update={
                "html": f"""<section style="display:grid;width:100%;height:100%;background:#111111;color:#ffffff;font-family:DM Sans,Inter,Arial,sans-serif;overflow:hidden;">
  <article style="display:grid;grid-template-rows:auto 1fr auto;gap:18px;width:100%;height:100%;padding:28px;background:#202020;">
    <header>
      <span style="display:inline-flex;align-items:center;border:1px solid rgba(255,255,255,.14);border-radius:999px;padding:6px 10px;color:rgba(255,255,255,.72);font-size:12px;">{escape(status)}</span>
      <h1 style="margin:14px 0 0;font-size:28px;line-height:1.16;">Comfy Runtime Check</h1>
      <p style="margin:8px 0 0;color:rgba(255,255,255,.68);font-size:14px;line-height:1.45;">comfy-diffusion diagnostic for future ComfyUI tools.</p>
    </header>
    <dl style="min-height:0;margin:0;overflow:auto;font-size:13px;line-height:1.4;">
{rows_html}
    </dl>
    <details style="border-top:1px solid rgba(255,255,255,.1);padding-top:12px;color:rgba(255,255,255,.68);font-size:12px;">
      <summary>Raw runtime info</summary>
      <pre style="overflow:auto;max-height:120px;margin:10px 0 0;color:rgba(255,255,255,.76);white-space:pre-wrap;">{raw_json}</pre>
    </details>
  </article>
</section>"""
            }
        )

        return ToolResult(cards=[card])

    def _format_megabytes(self, value: object) -> str:
        if isinstance(value, int | float):
            return f"{value:,.0f} MB"
        return "Unknown"


class HttpToolInvoker(ToolInvoker):
    def invoke(self, tool: ToolDefinition, payload: ToolInvocationRequest) -> ToolResult:
        if not tool.permissions.network:
            raise ToolInvocationError("Tool does not have network permission.")
        if not tool.runtime.entrypoint:
            raise ToolInvocationError("HTTP tool is missing an endpoint.")

        body = payload.model_dump(by_alias=True)
        http_request = request.Request(
            tool.runtime.entrypoint,
            data=json.dumps(body).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method=tool.runtime.method,
        )

        with request.urlopen(http_request, timeout=tool.runtime.timeout_seconds) as response:
            response_body = response.read().decode("utf-8")

        return ToolResult.model_validate_json(response_body)


class CliToolInvoker(ToolInvoker):
    def invoke(self, tool: ToolDefinition, payload: ToolInvocationRequest) -> ToolResult:
        if not tool.permissions.filesystem:
            raise ToolInvocationError("Tool does not have filesystem permission.")
        if not tool.runtime.command:
            raise ToolInvocationError("CLI tool is missing a command.")

        command_name = tool.runtime.command[0]
        if command_name not in tool.permissions.allowed_commands:
            raise ToolInvocationError("CLI command is not allowed by tool permissions.")

        completed_process = subprocess.run(
            tool.runtime.command,
            input=json.dumps(payload.model_dump(by_alias=True)),
            capture_output=True,
            check=False,
            encoding="utf-8",
            timeout=tool.runtime.timeout_seconds,
        )

        if completed_process.returncode != 0:
            raise ToolInvocationError(completed_process.stderr.strip() or "CLI tool failed.")

        return ToolResult.model_validate_json(completed_process.stdout)


class ToolInvokerFactory:
    def __init__(self) -> None:
        self._builtin = BuiltinToolInvoker()
        self._http = HttpToolInvoker()
        self._cli = CliToolInvoker()

    def get_invoker(self, source_type: str) -> ToolInvoker:
        if source_type == "builtin":
            return self._builtin
        if source_type == "http":
            return self._http
        if source_type in {"cli-local", "cli-remote"}:
            return self._cli

        raise ToolInvocationError(f"Unsupported tool source type: {source_type}")
