import json
import re
import subprocess
from abc import ABC, abstractmethod
from html import escape
from urllib import request

from app.models import ToolDefinition, ToolInvocationRequest, ToolResult
from app.services.card_factory import HtmlCardFactory


class ToolInvocationError(RuntimeError):
    pass


class ToolInvoker(ABC):
    @abstractmethod
    def invoke(self, tool: ToolDefinition, payload: ToolInvocationRequest) -> ToolResult:
        raise NotImplementedError


class BuiltinToolInvoker(ToolInvoker):
    def __init__(self, card_factory: HtmlCardFactory | None = None) -> None:
        self._card_factory = card_factory or HtmlCardFactory()

    def invoke(self, tool: ToolDefinition, payload: ToolInvocationRequest) -> ToolResult:
        if tool.id == "image" and isinstance(payload.params.get("imageDataUrl"), str):
            image_data_url = payload.params["imageDataUrl"]
            if not image_data_url.startswith("data:image/"):
                raise ToolInvocationError("imageDataUrl must be a data:image URL.")

            card = self._card_factory.create(
                prompt=payload.prompt,
                source_tool_id=tool.id,
                name=payload.params.get("name") or "Generated Image",
            )
            escaped_prompt = escape(payload.prompt)
            escaped_image_data_url = escape(image_data_url, quote=True)
            card = card.model_copy(
                update={
                    "html": f"""<section style="display:grid;width:100%;height:100%;place-items:center;background:#111111;color:#ffffff;font-family:DM Sans,Inter,Arial,sans-serif;overflow:hidden;">
  <figure style="display:grid;width:100%;height:100%;grid-template-rows:1fr auto;margin:0;background:#202020;">
    <div style="display:grid;min-height:0;place-items:center;padding:18px;">
      <img src="{escaped_image_data_url}" alt="{escaped_prompt}" style="display:block;max-width:100%;max-height:100%;object-fit:contain;border-radius:16px;" />
    </div>
    <figcaption style="padding:14px 18px 18px;color:rgba(255,255,255,.72);font-size:14px;line-height:1.45;">{escaped_prompt}</figcaption>
  </figure>
</section>"""
                }
            )
            return ToolResult(cards=[card])

        if tool.id == "hello-world":
            message = self._resolve_card_output_text(payload, fallback="Hello world")
            card = self._card_factory.create(
                prompt=payload.prompt,
                source_tool_id=tool.id,
                name="Hello World",
            )
            escaped_message = escape(message)
            card = card.model_copy(
                update={
                    "html": f"""<section style="display:grid;width:100%;height:100%;place-items:center;background:#111111;color:#ffffff;font-family:DM Sans,Inter,Arial,sans-serif;">
  <div style="display:grid;gap:8px;text-align:center;">
    <strong style="font-size:28px;line-height:1.2;">{escaped_message}</strong>
    <span style="color:rgba(255,255,255,.7);font-size:13px;">Generated by the Hello World built-in tool</span>
  </div>
</section>"""
                }
            )
            return ToolResult(cards=[card])

        card = self._card_factory.create(
            prompt=payload.prompt,
            source_tool_id=tool.id,
            name=f"{tool.name} card",
            output_text=self._resolve_card_output_text(payload, fallback=payload.prompt),
        )
        return ToolResult(cards=[card])

    def _resolve_card_output_text(self, payload: ToolInvocationRequest, *, fallback: str) -> str:
        for key in ("text", "message", "title", "content", "outputText"):
            value = payload.params.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()

        tool_prompt = payload.params.get("toolPrompt")
        prompt = tool_prompt.strip() if isinstance(tool_prompt, str) and tool_prompt.strip() else payload.prompt.strip()
        if not prompt:
            return fallback

        quoted_match = re.search(r"[\"'“”‘’]([^\"'“”‘’]{1,120})[\"'“”‘’]", prompt)
        if quoted_match:
            return quoted_match.group(1).strip()

        keyword_match = re.search(
            r"(?:diga|decir|diciendo|texto|contenido|says?|with text)\s+(?:exactamente\s+)?(.{1,120})",
            prompt,
            flags=re.IGNORECASE,
        )
        if keyword_match:
            message = keyword_match.group(1).strip()
            message = re.split(r"[.;\n]", message, maxsplit=1)[0].strip()
            message = message.strip(" \"'“”‘’")
            if message:
                return message

        return fallback


class HttpToolInvoker(ToolInvoker):
    def invoke(self, tool: ToolDefinition, payload: ToolInvocationRequest) -> ToolResult:
        if not tool.permissions.network:
            raise ToolInvocationError("Tool does not have network permission.")
        if not tool.runtime.entrypoint:
            raise ToolInvocationError("HTTP tool is missing an endpoint.")

        body = payload.model_dump(by_alias=True)
        http_request = request.Request(
            tool.runtime.entrypoint,
            data=json.dumps(body).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method=tool.runtime.method,
        )

        with request.urlopen(http_request, timeout=tool.runtime.timeout_seconds) as response:
            response_body = response.read().decode("utf-8")

        return ToolResult.model_validate_json(response_body)


class CliToolInvoker(ToolInvoker):
    def invoke(self, tool: ToolDefinition, payload: ToolInvocationRequest) -> ToolResult:
        if not tool.permissions.filesystem:
            raise ToolInvocationError("Tool does not have filesystem permission.")
        if not tool.runtime.command:
            raise ToolInvocationError("CLI tool is missing a command.")

        command_name = tool.runtime.command[0]
        if command_name not in tool.permissions.allowed_commands:
            raise ToolInvocationError("CLI command is not allowed by tool permissions.")

        completed_process = subprocess.run(
            tool.runtime.command,
            input=json.dumps(payload.model_dump(by_alias=True)),
            capture_output=True,
            check=False,
            encoding="utf-8",
            timeout=tool.runtime.timeout_seconds,
        )

        if completed_process.returncode != 0:
            raise ToolInvocationError(completed_process.stderr.strip() or "CLI tool failed.")

        return ToolResult.model_validate_json(completed_process.stdout)


class ToolInvokerFactory:
    def __init__(self) -> None:
        self._builtin = BuiltinToolInvoker()
        self._http = HttpToolInvoker()
        self._cli = CliToolInvoker()

    def get_invoker(self, source_type: str) -> ToolInvoker:
        if source_type == "builtin":
            return self._builtin
        if source_type == "http":
            return self._http
        if source_type in {"cli-local", "cli-remote"}:
            return self._cli

        raise ToolInvocationError(f"Unsupported tool source type: {source_type}")
